#!/bin/bash

build() {
    add_binary "/usr/local/bin/vtoydump"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook includes the vtoydump binary and script to mount the root partition by information passed by ventoy.
HELPEOF
}
